### ISSUE TITLE
Crashing loop unknown was not awaken when player made it happen.

### ISSUE THREAD

**Issue by foofookiller** [lucaargolo/extra-generators#1]
[crash-2021-06-21_23.04.05-server.txt](https://github.com/lucaargolo/extra-generators/files/6689930/crash-2021-06-21_23.04.05-server.txt)

**Comment by lucaargolo** [comment]
This was already fixed, just published the update on CurseForge.
https://www.curseforge.com/minecraft/mc-mods/extra-generators/files/3360524

**Comment by foofookiller** [comment]
thank you. sorry for not knowing it was already fixed.
