### ISSUE TITLE
Thermoelectric Generator spams packets to players

### ISSUE THREAD

**Issue by Tomatobird8** [lucaargolo/extra-generators#2]
The Thermoelectric Generator block spams packets to all players who have the chunks loaded that the generator block is in. With bigger power farms the server needs to upload many megabytes of packets to any players nearby.

Tested in modpack AoF3 (1.16.5, extra-generators-1.0.2-BETA+1.16), and with extra-generators-1.0.5-BETA+1.17 on a fresh server.

Video: https://streamable.com/h9lvje
Send/Recieve are the networking stats of the computer my client + server was running. Note how Send rises as more Thermoelectric Generators are placed in the world.

**Comment by lucaargolo** [comment]
Thanks for the detailed issue report with a video explaining and showing the problem! It really helps. This issue should now be fixed on 1.16.5 using version 1.0.3-BETA, and on 1.17 using version 1.0.6-BETA. Both should be approved really soon on CurseForge.
