### ISSUE TITLE
Also move energy into targets that allow insertion, but have capacity=0

### ISSUE THREAD

**Issue by shartte** [lucaargolo/extra-generators#7]
https://github.com/lucaargolo/extra-generators/blob/bd6948b9610efa2aea89c46fc43ac0cddf6640b7/src/main/kotlin/io/github/lucaargolo/extragenerators/common/blockentity/AbstractGeneratorBlockEntity.kt#L156

This is the case for AE2 energy acceptors since they don't actually have a capacity. They forward energy into the internal grid using an invisible buffer that has no bound.

Check could be

```java
if(target.supportsInsertion() && (target.amount < target.capacity || target.capacity == 0)) {
```

**Comment by Technici4n** [comment]
You can just omit the capacity check altogether.
